global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: otel-collector-a
    static_configs:
      - targets: ["otel-collector-a:8888"]

  - job_name: service-a
    static_configs:
      - targets: ["otel-collector-a:9464"]

  - job_name: otel-collector-b
    static_configs:
      - targets: ["otel-collector-b:8888"]

  - job_name: service-b
    static_configs:
      - targets: ["otel-collector-b:9464"]
