<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>edu.unisabana.otel</groupId>
  <artifactId>company-otel-business</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>

  <modules>
    <module>company-otel-core</module>
    <module>company-otel-jboss-mdc</module>
    <module>company-otel-aspectj</module>
  </modules>

  <properties>
    <aspectj.version>1.9.22.1</aspectj.version>
    <junit.version>5.11.4</junit.version>
    <maven.compiler.release>17</maven.compiler.release>
    <opentelemetry.version>1.46.0</opentelemetry.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <surefire-plugin.version>3.5.2</surefire-plugin.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-bom</artifactId>
        <version>${opentelemetry.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.13.0</version>
          <configuration>
            <parameters>true</parameters>
            <release>${maven.compiler.release}</release>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${surefire-plugin.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
