company.otel.max-attribute-length=256
company.otel.redacted-fields=password,secret,token,authorization,cvv,pan,creditCard,accessToken,refreshToken

otel.company.order.process.enabled=true
otel.company.order.process.span.name=process order
otel.company.order.process.record.exceptions=true
otel.company.order.process.capture.result=true
otel.company.order.process.attr.company.order.id=#orderId
otel.company.order.process.attr.company.order.status=#result.status
otel.company.order.process.attr.company.product.id=#result.product.productId
otel.company.order.process.attr.company.product.name=#result.product.name
